# ============================
# Site
# ============================
title      : "SuperFriendly"
description: ""
url        : ""  # the base hostname & protocol for your site

# ============================
# Author
# ============================
email: ""
twitter_username: ""

# ============================
# Serving
# ============================
detach: false
port: 4000
host: 127.0.0.1
baseurl: "" #does not include hostname

# ============================
# Backwards compatibility
# ============================
# relative_permalinks: false

# ============================
# Outputting
# ============================
# paginate     : 10
# permalink    : /blog/:title
# paginate_path: /page/:num
# timezone     :      null

# quiet:    false
# defaults: []

# ============================
# Where things are
# ============================
# source:      .
# destination: ./_site
# plugins:     ./_plugins
# layouts:     ./_layouts
# data_source: ./_data

# ============================
# Handling reading
# ============================
# safe:         false
# include:      [".htaccess"]
exclude: [
  "assets/sass",
  "assets/js/src",
  "assets/js/vendor",
  "bower.json",
  "bower_components",
  "Gemfile",
  "Gemfile.lock",
  "Gruntfile.js",
  "node_modules",
  "package.json"
]
# keep_files:   [".git", ".svn"]
encoding:     "utf-8"
# markdown_ext: "markdown,mkdown,mkdn,mkd,md"
# textile_ext:  "textile"

# ============================
# Filtering
# ============================
# show_drafts: null
# limit_posts: 0
# future:      true
# unpublished: false

# ============================
# Plugins
# ============================
# whitelist: []
# gems:      []

# ============================
# Conversion
# ============================
markdown         : kramdown
highlighter      : pygments
# lsi              : true
# excerpt_separator: <!--more-->

# ============================
# Markdown Processors
# ============================
kramdown:
  auto_ids:      true
  # footnote_nr:   1
  # entity_output: as_char
  # toc_levels:    1..6
  # smart_quotes:  lsquo,rsquo,ldquo,rdquo
  # use_coderay:   false

  # coderay:
  #   coderay_wrap:              div
  #   coderay_line_numbers:      inline
  #   coderay_line_number_start: 1
  #   coderay_tab_width:         4
  #   coderay_bold_every:        10
  #   coderay_css:               style